{% set name = "des-pixcorrect" %}
{% set version = "3.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DarkEnergySurvey/pixcorrect/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9ba1dd674e56b4473ae710dbe4e180379baa6113eef978864b609fac70293556
  patches:
    - mask_sat.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - des-imsupport-dev
    - des-despyfits
  run:
    - python
    - numpy
    - scipy
    - fitsio
    - des-despyastro
    - des-despymisc
    - des-despyfits

test:
  commands:
    - test -f ${PREFIX}/pixcorrect/include/libfixcol.h
    - test -f ${PREFIX}/pixcorrect/lib/libbiascorrect{{ SHLIB_EXT }}
    - test -f ${PREFIX}/pixcorrect/lib/libbpm{{ SHLIB_EXT }}
    - test -f ${PREFIX}/pixcorrect/lib/libfixcol{{ SHLIB_EXT }}
    - test -f ${PREFIX}/pixcorrect/lib/libflatcorrect{{ SHLIB_EXT }}
    - test -f ${PREFIX}/pixcorrect/lib/libmasksatr{{ SHLIB_EXT }}
    - test -f ${PREFIX}/pixcorrect/lib/libfpnumber{{ SHLIB_EXT }}
    - coadd_nwgint --help
  imports:
    - pixcorrect
    - pixcorrect.mask_saturation

about:
  home: https://github.com/DarkEnergySurvey/pixcorrect
  summary: DES Image software
  license: NCSA
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
